//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miCrudMvc3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int cod_usu { get; set; }
        public string nom_usu { get; set; }
        public Nullable<int> car_cod { get; set; }
    
        public virtual cargo cargo { get; set; }
    }
}
