#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miCrudMvc4.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_empresa")]
	public partial class DataEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertarea(area instance);
    partial void Updatearea(area instance);
    partial void Deletearea(area instance);
    #endregion
		
		public DataEmpresaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_empresaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<area> areas
		{
			get
			{
				return this.GetTable<area>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_DELETEAREA")]
		public int PR_DELETEAREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> are_cod)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), are_cod);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_INSERTAREA")]
		public int PR_INSERTAREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string are_des)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), are_des);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_SEARCHAREA")]
		public ISingleResult<PR_SEARCHAREAResult> PR_SEARCHAREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> are_cod)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), are_cod);
			return ((ISingleResult<PR_SEARCHAREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_UPDATEAREA")]
		public int PR_UPDATEAREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> are_cod, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string are_des)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), are_cod, are_des);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.area")]
	public partial class area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _are_cod;
		
		private string _are_des;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onare_codChanging(int value);
    partial void Onare_codChanged();
    partial void Onare_desChanging(string value);
    partial void Onare_desChanged();
    #endregion
		
		public area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int are_cod
		{
			get
			{
				return this._are_cod;
			}
			set
			{
				if ((this._are_cod != value))
				{
					this.Onare_codChanging(value);
					this.SendPropertyChanging();
					this._are_cod = value;
					this.SendPropertyChanged("are_cod");
					this.Onare_codChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_des", DbType="VarChar(50)")]
		public string are_des
		{
			get
			{
				return this._are_des;
			}
			set
			{
				if ((this._are_des != value))
				{
					this.Onare_desChanging(value);
					this.SendPropertyChanging();
					this._are_des = value;
					this.SendPropertyChanged("are_des");
					this.Onare_desChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PR_SEARCHAREAResult
	{
		
		private int _are_cod;
		
		private string _are_des;
		
		public PR_SEARCHAREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_cod", DbType="Int NOT NULL")]
		public int are_cod
		{
			get
			{
				return this._are_cod;
			}
			set
			{
				if ((this._are_cod != value))
				{
					this._are_cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_des", DbType="VarChar(50)")]
		public string are_des
		{
			get
			{
				return this._are_des;
			}
			set
			{
				if ((this._are_des != value))
				{
					this._are_des = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
